apiVersion: v1
kind: Service
metadata:
  name: car-rental-service-lb
spec:
  selector:
    app: car-rental-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
